import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shopping List",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full bg-slate-900 text-white p-4">
          <div className="mx-auto flex max-w-6xl items-center justify-between">
            <div className="text-lg font-semibold">Shopping List</div>
            <Link
              href="/"
              className="rounded-md bg-slate-700 px-4 py-2 text-sm font-medium hover:bg-slate-600"
            >
              Return to home
            </Link>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
